### PR TITLE
Fixed speed slider service call

### LINKED ISSUE #89: IO Controller: Setting speed slider to 1.0
Currently the speed slider cannot be set to 100%. The controller seems to accept the input but on the call to the hardware interface something seems to go wrong. Thus the request is ignored

### PR DESCRIPTION
**Pull request by MGBla**
Fixes #89 and #90

### CODE REVIEW

File: ur_controllers/src/gpio_controller.cpp [hunk 1]
```diff
@@ -263,22 +263,23 @@ bool GPIOController::setIO(ur_msgs::srv::SetIO::Request::SharedPtr req, ur_msgs:
...
     // reset success flag
-    command_interfaces_[CommandInterfaces::SCALING_ASYNC_SUCCESS].set_value(2.0);
+    command_interfaces_[CommandInterfaces::TARGET_SPEED_FRACTION_ASYNC_SUCCESS].set_value(2.0);
     // set commanding value for speed slider
-    command_interfaces_[CommandInterfaces::SPEED_SCALING_CMD].set_value(
+    command_interfaces_[CommandInterfaces::TARGET_SPEED_FRACTION_CMD].set_value(
         static_cast<double>(req->speed_slider_fraction));
 
-    while (command_interfaces_[CommandInterfaces::SCALING_ASYNC_SUCCESS].get_value() != 2.0) {
+    while (command_interfaces_[CommandInterfaces::TARGET_SPEED_FRACTION_ASYNC_SUCCESS].get_value() != 2.0) {
```
Comment (urrsk) [inline ur_controllers/src/gpio_controller.cpp:274]: Please define use constants for numbers that have a specific meaning.

**Review by urrsk — CHANGES_REQUESTED** [review]
2.0 and -1 seems to be constants with a specific meaning. Please define them as constants with a meaningful name, and use that instead. It will also make the code more readable.

File: ur_controllers/src/gpio_controller.cpp (hunk 1 above)
Comment (MGBla) [reply ur_controllers/src/gpio_controller.cpp:274]: Changed it so that the shared cmd variable contains a NaN if no new data is available and capsuled it into a static constant

Comment (MGBla) [reply ur_controllers/src/gpio_controller.cpp:274]: Ok still have to have a look at what @livanov93 intended with the async communication at this point.

Comment (MGBla) [reply ur_controllers/src/gpio_controller.cpp]: Exchanged 2.0 value as well and removed a race condition between controller and hardware interface in the async check

**Review by urrsk — APPROVED** [review]
Looks good
